### ISSUE TITLE
Table 1 - payload #bits

### ISSUE THREAD

**Issue by ved-rivos** [riscv-non-isa/e-trace-encap#10]
The # Bits for payload should be 2 to 248 as the type must be >= 2.

**Comment by IainCRobertson** [comment]
Yes, and I'll fix that subject to the outcome of the Issue #9 discussion.  The point I was trying to convey here was that a length of 0 is not allowed (as header.length cannot be 0 in a normal packet).

**Comment by IainCRobertson** [comment]
Following updates for Issue #9, original definition of payload width (1-248 bits) is correct, and no further action is required.
