### ISSUE TITLE
Clarify null packets total size as one byte

### ISSUE THREAD

**Issue by ved-rivos** [riscv-non-isa/e-trace-encap#17]
The current phrasing, "A null packet is defined as a single header byte with a zero length field," could be misinterpreted. To unequivocally state that a null packet is composed of only a single byte, we suggest the following rewording: "A null packet is specified as consisting exclusively of one header byte, with its length field set to zero, explicitly indicating the packet's total size as one byte.". This adjustment aims to eliminate any ambiguity regarding the packet's composition.

**Comment by IainCRobertson** [comment]
Updated as suggested and PR created.

**Comment by ved-rivos** [comment]
Thanks. LGTM.
