### ISSUE TITLE
Incorrect name on trRamAsyncFreq

### ISSUE THREAD

**Issue by pdonahue-ventana** [riscv-non-isa/e-trace-encap#2]
Section 3.4 refers to "trRamSinkAsyncFreq" but the [RISC-V Trace Control Interface Specification](https://github.com/riscv-non-isa/tg-nexus-trace/blob/master/docs/RISC-V-Trace-Control-Interface.adoc?plain=1#L1087) calls it "trRamAsyncFreq"

**Comment by IainCRobertson** [comment]
Fixed in commit c75acb9e70166ee83bf97bd8c0ac713f9c53748f
