### ISSUE TITLE
Beeman v1.0.2 internal review feedback

### ISSUE THREAD

**Issue by bcstrongx** [riscv-non-isa/e-trace-encap#3]
1. I would expand LSB.  It can be unclear whether B is bit or byte, but also seems inappropriate for a spec.
2. In 2.1 I see "The groups are defined in the following tables:", but tables do not immediately follow.  Probably should say "following sections."?
3. 2.1.1: "The header is a single byte comprising the fields defined in Table 2." should be "The header is a single byte comprised of the fields defined in Table 2."
4. 2.1.1: Once I got to the null encapsulation section I learned why you say here that length only supports 1..31 (vs 0..31 or 1..32), but it would be best to clarify here that length=N means N-byte payload, rather than values 0..30 corresponding to lengths 1..31.  
5. 2.1.1: "Reserved if timestamp width is 0".  Should be explicit that reserved means value 0.  Maybe just "Reserved (0) ..."
6. 2.1.4: "Maximum value of R is defined as 248 - Y - srcID%8 where Y is the length of the type field." This is confusing, it hasn't been explained yet.  Would be good to say in srcID section that any bits beyond multiples of 8 come out of the payload size.
7. 2.2: Explain that the 8 types of null packets make use of the flow and extend fields of the header.

**Comment by bcstrongx** [comment]
Also, version shouldn't be v1.0 until ratified.

**Comment by pdonahue-ventana** [comment]
> 2.1.1: "The header is a single byte comprising the fields defined in Table 2." should be "The header is a single byte comprised of the fields defined in Table 2."

Uh oh.  You're going to open the "comprised of" can of worms.  https://www.grammarly.com/blog/comprise-vs-compose/

**Comment by bcstrongx** [comment]
Ack!  Well that's embarrassing.  Ignore that one I guess.

**Comment by IainCRobertson** [comment]
Wasn't actually subscribed to receive notifications, so only just seen this...

Will address and issue a new draft

**Comment by IainCRobertson** [comment]
1, 2, 4, 5, 7: done
3: not done :-)
6:  Tricky one.  I was trying to avoid getting bogged down in too much detail until after the basic structure and field definitions, which is why the 'Packet Length' section comes after the 'Payload Fields' section.  I still think that makes sense, but I've tweaked the wording in the 'SrcID' section, added an explicit reference in the trace_payload field description, and added a final extra sentence to the 'Packet Length' section.  Hopefully this addresses your concerns

**Comment by IainCRobertson** [comment]
Beeman happy with the results (replied by direct email)
