### ISSUE TITLE
Null encapsulation and flow

### ISSUE THREAD

**Issue by ved-rivos** [riscv-non-isa/e-trace-encap#5]
The flow field is used to direct packets to a particular sink in the system when multiple sinks exist. However, the null encapsulation requires that the flow field be set to 0. When multiple sinks exist, how does the sink picked by a non-zero flow encoding get the idle and alignment packets to synchronize to the packet stream it will eventually receive with a non-zero flow value?

**Comment by ved-rivos** [comment]
A related issue is this definition:
> A null packet is defined as a single header byte with a zero length field. The remaining header fields (flow and extend) allow for up to 8 different types of null packet

If the flow is included in the encoding of type of null packets then how are these null packets intended to be routed to the right sink as the flow field now gets redefined.

**Comment by IainCRobertson** [comment]
Good question.  My expectation (based on the way the Siemens encapsulation on which this is based is used) is that idle packets are not generated at source, but are generated at the sink.  Packets emitted from the source are generally transported over some form of on-chip trace bus (e.g. ATB).  Such buses have various sideband signals, including 'valid' , and so there is generally no need to send idle packets.  At the sink, the packets have to be combined into a data stream that typically doesn't have a 'valid', and this is where idle packets need to be inserted.  At this point there is no further need for the 'flow' information.

That being said, it would be more general to tweak the definition here to preserve the 'flow' field in idle packets, which would allow for idles to be generated at source if such a need ever arises.  I am happy to do that.  I will also include a paragraph covering the explanation above.

**Comment by ved-rivos** [comment]
If we preserve `flow` in idle packets then we also need to update the null packet definition. Only 2 null packets are possible.

**Comment by IainCRobertson** [comment]
Yes, that was my intent.
