### ISSUE TITLE
Why is trAtbBridgeAsyncFreq not applicable for E-trace?

### ISSUE THREAD

**Issue by ved-rivos** [riscv-non-isa/e-trace-encap#6]
The trPibAsyncFreq and trRamAsyncFreq are specified as providing the interval between synchronization sequence insertion for E-trace packets but the trAtbBridgeAsyncFreq is omitted. Is that intentional? If so why is it not applicable?

**Comment by IainCRobertson** [comment]
Sorry, this is an oversight.  I'll fix

**Comment by IainCRobertson** [comment]
Fixed (sorry - user error with VSCode means I committed straight to main rather than via PR).  Change was trivial though.
