### ISSUE TITLE
Inclusion of timestamp

### ISSUE THREAD

**Issue by ved-rivos** [riscv-non-isa/e-trace-encap#7]
Section 2.1.3 indicates that timestamp may be omitted if time information is already included within the encapsulated payload. Section 3.2 states that the header.extend is set to the value of trTsEnable implying that there is no option of omitting the header.timestamp for E-trace if trTsEnable is 1 even for payloads that include a time field. The text in 3.2 further uses terminology such as "an alternative method of providing time". Which interpretation is correct?

**Comment by IainCRobertson** [comment]
I don't see an inconsistency here.  trTsEnable determines whether a timestamp is included in the encapsulation. The references to time being included in the payload relate to optional capabilities included in the E-Trace spec related to time.  These allow for timestamps to be optionally included in all sync packets, and also allow for 'time' packets, though these are not defined beyond this.  If anyone had implemented these capabilities then they may not want to include timestamps in the packet encapsulation as well.

**Comment by ved-rivos** [comment]
Clarifying the text to state that when trTsEnable is 1, a timestamp may be optionally included and if included the header.extend is set to 1 would suffice.
