### ISSUE TITLE
Padding bits

### ISSUE THREAD

**Issue by ved-rivos** [riscv-non-isa/e-trace-encap#8]
Encapsulated packets are a number of whole bytes in length. 
When the (#bits(payload) + #bits(srcID)%8) is not a multiple of 8 then up to 7 padding bits seem to be included to make the encapsulated packet length a multiple of 8 bytes. 
However, the document does not specify the position or the value of the padding bits.

**Comment by IainCRobertson** [comment]
The presence of 'padding bits' is not related to whether the SrcID is a multiple of 8 or not.  The trace_payload field length is defined in bits, not bytes, and any time the payload and 'leftover' SrcID bits are not a multiple of 8 bits there will be some "don't care" bits at the top of the final byte of the packet.  

This is one of those "obvious" things that isn't so obvious - I'll make this explicit.

**Comment by ved-rivos** [comment]
Its unrelated to srcID and is why I the equation has two terms. Clarifying the pad bits being the MS bits would be good. Either requiring that the pad bits be always 0/1 or guiding that pad bits should not leak the previous contents of a intermediate buffer may be useful to avoid leaking up to 7 bits of data from a previous trace session.
